# Generated by Django 5.0.6 on 2025-04-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_technicalmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='ems_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
